--Inserimento ingredienti di esempio
INSERT INTO ingrediente (nome, unit_misura) VALUES
('Farina', 'Kg'),
('Uova', 'Pz'),
('Burro', 'Kg'),
('Cioccolato', 'Kg'),
('Zucchero', 'Kg'),
('Latte', 'L');


--Inserimento ricette di esempio
INSERT INTO ricetta (nome, descrizione) VALUES
('Pasta Fresca', 'Ricetta per preparare la pasta fresca fatta in casa.'),
('Torta al Cioccolato', 'Deliziosa torta al cioccolato per ogni occasione.'),
('Risotto ai Funghi', 'Ricetta classica per un risotto cremoso ai funghi.'),
('Insalata Caprese', 'Fresca insalata con pomodoro, mozzarella e basilico.'),
('Lasagna alla Bolognese', 'Lasagna ricca con ragù alla bolognese e besciamella.'),
('Tiramisu', 'Dessert italiano a base di mascarpone, caffè e savoiardi.'),
('Pizza Margherita', 'Classica pizza con pomodoro, mozzarella e basilico.'),
('Pollo al Curry', 'Ricetta speziata per un pollo al curry saporito.'),
('Zuppa di Lenticchie', 'Zuppa nutriente a base di lenticchie e verdure.'),
('Pennette al Pomodoro', 'Semplice e gustosa ricetta di pennette al pomodoro.'),
('Noodles', 'Ricetta per preparare noodles fatti in casa.'),
('Sfilettatura', 'Guida passo passo per sfilettare il pesce.'),
('Poke con Uova e Tofu', 'Insalata poke con uova sode, tofu e verdure fresche.'),
('Polpette vegetali', 'Pasta di ceci e condimenti dolci'),
('Arancino agli spinaci', 'Arancino con ripieno di spinaci'),
('Bubble tea', 'Tè freddo con perle di tapioca'),
('Couscous con verdure', 'Couscous con verdure miste e spezie'),
('Hamburger vegetariano', 'Hamburger a base di legumi e verdure'),
('Pasta al pesto', 'Pasta con salsa al pesto fatta in casa'),
('Riso alla cantonese', 'Riso saltato con uova, piselli e prosciutto cotto');



--Inserimento necessita di esempio
INSERT INTO necessita (ricetta_id, ingrediente_id, quant_ing) VALUES
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta Fresca'), 'Farina', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta Fresca'), 'Uova', 3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato'), 'Burro', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato'), 'Cioccolato', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato'), 'Zucchero', 0.25),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato'), 'Latte', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi'), 'Riso', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi'), 'Funghi', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi'), 'Brodo', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese'), 'Pomodoro', 2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese'), 'Mozzarella', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese'), 'Basilico', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Lasagna alla Bolognese'), 'Pasta per lasagna', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Lasagna alla Bolognese'), 'Ragù alla bolognese', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Lasagna alla Bolognese'), 'Besciamella', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Tiramisu'), 'Mascarpone', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Tiramisu'), 'Caffè', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Tiramisu'), 'Savoiardi', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pizza Margherita'), 'Farina', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pizza Margherita'), 'Pomodoro', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pizza Margherita'), 'Mozzarella', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pizza Margherita'), 'Basilico', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pollo al Curry'), 'Pollo', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pollo al Curry'), 'Curry in polvere', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pollo al Curry'), 'Latte di cocco', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie'), 'Lenticchie', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie'), 'Verdure miste', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie'), 'Brodo', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pennette al Pomodoro'), 'Pennette', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pennette al Pomodoro'), 'Pomodoro', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pennette al Pomodoro'), 'Basilico', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Noodles'), 'Farina', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Noodles'), 'Uova', 2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Sfilettatura'), 'Pesce', 1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Riso', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Uova', 2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Tofu', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Polpette vegetali'), 'Ceci', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Polpette vegetali'), 'Salsine', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Arancino agli spinaci'), 'Riso', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Arancino agli spinaci'), 'Spinaci', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Bubble tea'), 'Tè freddo', 0.5),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Bubble tea'), 'Perle di tapioca', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Couscous con verdure'), 'Couscous', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Couscous con verdure'), 'Verdure miste', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Hamburger vegetariano'), 'Legumi', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Hamburger vegetariano'), 'Verdure', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta al pesto'), 'Pasta', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta al pesto'), 'Salsa al pesto', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese'), 'Riso', 0.4),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese'), 'Uova', 2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese'), 'Piselli', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese'), 'Prosciutto cotto', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Tofu', 0.3),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Verdure fresche', 0.2),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Soia', 0.1),
((SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu'), 'Riso', 0.3);



 