 --inserimento pratica di esempio
INSERT INTO pratica (giorno_sessione, aula, corso_id, posti_totali) 
VALUES (CURRENT_DATE + INTERVAL '2 days', 'Aula 101', (SELECT id_corso FROM corso WHERE nome = 'Corso di Pasta Fresca'), 30),
    (CURRENT_DATE + INTERVAL '4 days', 'Aula 102', (SELECT id_corso FROM corso WHERE nome = 'Corso di Pasta Fresca'), 25),
    (CURRENT_DATE + INTERVAL '136 days', 'Aula 201', (SELECT id_corso FROM corso WHERE nome = 'Corso di Pasticceria Base'), 20),
    (CURRENT_DATE + INTERVAL '138 days', 'Aula 202', (SELECT id_corso FROM corso WHERE nome = 'Corso di Pasticceria Base'), 15),
    (CURRENT_DATE + INTERVAL '12 days', 'Aula 301', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Principianti'), 40),
    (CURRENT_DATE + INTERVAL '14 days', 'Aula 302', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Principianti'), 35),
    (CURRENT_DATE + INTERVAL '155 days', 'Aula 401', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Tradizionale'), 30),
    (CURRENT_DATE + INTERVAL '155 days', 'Aula 402', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Tradizionale'), 25),
    (CURRENT_DATE + INTERVAL '17 days', 'Aula 501', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Vegetariana'), 20),
    (CURRENT_DATE + INTERVAL '17 days', 'Aula 502', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Vegetariana'), 15),
    (CURRENT_DATE + INTERVAL '32 days', 'Aula 601', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Vegana'), 25),
    (CURRENT_DATE + INTERVAL '32 days', 'Aula 602', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Vegana'), 20),
    (CURRENT_DATE + INTERVAL '110 days', 'Aula 701', (SELECT id_corso FROM corso WHERE nome = 'Corso di Sfilettatura'), 15),
    (CURRENT_DATE + INTERVAL '110 days', 'Aula 702', (SELECT id_corso FROM corso WHERE nome = 'Corso di Sfilettatura'), 10),
    (CURRENT_DATE + INTERVAL '42 days', 'Aula 801', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Celiaca'), 20),
    (CURRENT_DATE + INTERVAL '42 days', 'Aula 802', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Celiaca'), 15),
    (CURRENT_DATE + INTERVAL '57 days', 'Aula 901', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Diabetici'), 25),
    (CURRENT_DATE + INTERVAL '57 days', 'Aula 902', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Diabetici'), 20),
    (CURRENT_DATE + INTERVAL '12 days', 'Aula 1001', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Principianti'), 40),
    (CURRENT_DATE + INTERVAL '12 days', 'Aula 1002', (SELECT id_corso FROM corso WHERE nome = 'Corso di Arancini'), 35),
    (CURRENT_DATE + INTERVAL '37 days', 'Aula 1101', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Anziani'), 30),
    (CURRENT_DATE + INTERVAL '37 days', 'Aula 1102', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina per Anziani'), 25),
    (CURRENT_DATE + INTERVAL '155 days', 'Aula 1201', (SELECT id_corso FROM corso WHERE nome = 'Corso di Cucina Cinese'), 30);



--update data d'inizio corso
UPDATE corso SET data_in = CURRENT_DATE + INTERVAL '1 days' WHERE nome = 'Corso di Pasta Fresca';
UPDATE corso SET data_in = CURRENT_DATE + INTERVAL '1 days' WHERE nome = 'Corso di Pasticceria Base';

--inserimento iscritto_p di esempio
INSERT INTO iscritto_p (stud_id, pratica_id) 
VALUES ('MFerraro', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '2 days' AND aula = 'Aula 101')),
    ('MFerraro', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '4 days' AND aula = 'Aula 102')),
    ('MFerraro', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '136 days' AND aula = 'Aula 201')),
    ('LBianchi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '4 days' AND aula = 'Aula 102')),
    ('LBianchi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '136 days' AND aula = 'Aula 201')),
    ('JDoe', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 301')),
    ('RVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 301')),
    ('CDeMarco', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '17 days' AND aula = 'Aula 501')),
    ('MS Rossi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '17 days' AND aula = 'Aula 501')),
    ('FBruno', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '32 days' AND aula = 'Aula 601')),
    ('LVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '32 days' AND aula = 'Aula 601')),
    ('Lverdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 1001')),
    ('FBruno', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 1001')),
    ('RVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '37 days' AND aula = 'Aula 1101')),
    ('CDeMarco', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '37 days' AND aula = 'Aula 1101')),
    ('MS Rossi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 701')),
    ('FBruno', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 701')),
    ('LVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 701')),
    ('RVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 801')),
    ('CDeMarco', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 801')),
    ('MS Rossi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 801')),
    ('JDoe', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 901')),
    ('RVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 901')),
    ('CDeMarco', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 901')),
    ('MS Rossi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 401')),
    ('FBruno', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 401')),
    ('LVerdi', (SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 401'));

--inserimento pratica_svolta di esempio
INSERT INTO pratica_svolta (pratica_id, ricetta_id)
VALUES ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '2 days' AND aula = 'Aula 101'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta Fresca')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '4 days' AND aula = 'Aula 102'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta Fresca')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '2 days' AND aula = 'Aula 101'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '4 days' AND aula = 'Aula 102'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '136 days' AND aula = 'Aula 201'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta Fresca')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '138 days' AND aula = 'Aula 202'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Torta al Cioccolato')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 301'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 301'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '14 days' AND aula = 'Aula 302'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Lasagna alla Bolognese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '14 days' AND aula = 'Aula 302'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pennette al Pomodoro')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '17 days' AND aula = 'Aula 501'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '17 days' AND aula = 'Aula 501'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta al pesto')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '17 days' AND aula = 'Aula 502'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Hamburger vegetariano')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '32 days' AND aula = 'Aula 601'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Polpette vegetali')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '32 days' AND aula = 'Aula 601'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Couscous con verdure')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '32 days' AND aula = 'Aula 602'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Arancino agli spinaci')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 701'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Sfilettatura')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 701'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Poke con Uova e Tofu')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '110 days' AND aula = 'Aula 702'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pollo al Curry')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 801'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 801'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pasta al pesto')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '42 days' AND aula = 'Aula 802'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 901'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 901'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '57 days' AND aula = 'Aula 902'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pizza Margherita')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 401'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Arancino agli spinaci')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 401'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Noodles')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 402'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 1001'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Risotto ai Funghi')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 1001'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Lasagna alla Bolognese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '12 days' AND aula = 'Aula 1002'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Arancino agli spinaci')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '37 days' AND aula = 'Aula 1101'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Zuppa di Lenticchie')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '37 days' AND aula = 'Aula 1101'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Pennette al Pomodoro')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '37 days' AND aula = 'Aula 1102'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Insalata Caprese')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 1201'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Noodles')),
    ((SELECT id_pratica FROM pratica WHERE giorno_sessione = CURRENT_DATE + INTERVAL '155 days' AND aula = 'Aula 1201'), (SELECT id_ricetta FROM ricetta WHERE nome = 'Riso alla cantonese'));
